- name: Delete RG and VM
  hosts: localhost
  connection: local
  tasks:
  - name: Delete resource group
    azure_rm_resourcegroup:
      name: table4jbansiblerg
      location: ukwest
      state: absent
      force: yes
