- hosts: localhost
  connection: local
  vars: 
    group: table4jbwebapprg
    webapp_name: table4jbwebapp
    location: ukwest
  tasks:
    - name: create rg
      azure_rm_resourcegroup:
        name: "{{group}}"
        location: "{{location}}"
        state: absent
        force: yes
